[tool.poetry]
name = "kinetic-sdk"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
openapi-client = {path = "src/generated/openapi-client"}
solana = "^0.27.2"
pybase64 = "^1.2.2"
solders = "0.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
