[tool.poetry]
name = "kinetic-sdk"
version = "1.0.0-rc.1"
description = ""
authors = ["Kin Foundation <dev@kin.org>"]

[tool.poetry.dependencies]
python = "^3.8"
solana = "^0.27.2"
pybase64 = "^1.2.2"
solders = "0.9.3"
kinetic-api-client = "^1.0.0-rc.1" 
# kinetic-api-client = {path = "src/generated/kinetic-api-client"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
